### PR TITLE
Add `total_delay` to handler arguments

### PR DESCRIPTION
**Pull request by mmazour**
Pass the total time waited to the handler.  This is to facilitate, for example,
bumping a stat or emitting a warning when delays exceed a threshold.

Includes test, and README change.

### CODE REVIEW

**Comment by cespare** [comment]
Hi @mmazour, thanks for this change. See the comments I've made -- otherwise, it looks good to me. I'll merge and push a new gem version if you can address the comments.

**Comment by mmazour** [comment]
Thanks very much, @cespare.  I've now added a commit with the changes you suggested.  (I also wrapped a line in one of your tests to make it visually consistent with the line of mine that had to be wrapped; hope that's OK.)

Tests now run in ~ 0.11s - 0.14s for me; is that quick enough?  I can dial the timings down tighter if you like, but I didn't want to push too hard and wind up with false failures on (for example) a slightly hiccup-prone older laptop.

**Comment by cespare** [comment]
Hi @mmazour,

I merged the change. I went ahead and made the test completely timing-independent in d865b74f4f4754af32ad8ab48b38e504e4e4803a; let me know what you think. I've also pushed 0.0.4 to Rubygems.

**Comment by mmazour** [comment]
Cool.  Thanks very much!

```
Michael
```

On 12 March 2013 23:03, Caleb Spare notifications@github.com wrote:

> Hi @mmazour https://github.com/mmazour,
> 
> I merged the change. I went ahead and made the test completely
> timing-independent in d865b74https://github.com/ooyala/retries/commit/d865b74f4f4754af32ad8ab48b38e504e4e4803a;
> let me know what you think. I've also pushed 0.0.4 to Rubygems.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ooyala/retries/pull/1#issuecomment-14811661
> .

## 

Global Personals is a limited company registered in England and Wales.

Registered number: 04880697

Registered office: Minton Place, Victoria Street, Windsor, Berkshire, SL4 
1EG, United Kingdom

**Pull request merged**
